# Problem1 Vandermonde.

In [17]:
import numpy as np
def vanderonde_matrix(input_vector,n,order = False):
    if order == True:
        out = np.array([x ** i for x in input_vector for i in range(n)]).reshape(len(input_vector),n)
        
    elif order == False :
        out = np.array([x ** (n-1-i) for x in input_vector for i in range(n)]).reshape(len(input_vector),n)
       
              
        
    return out
        
input_vector = [1,2,3,4,5]
n=3
        
print(vanderonde_matrix(input_vector,n,True) )    
print(vanderonde_matrix(input_vector,n,False) ) 

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


#  Problem 2 Moving Average

In [18]:

def moving_average(x, w):
    return np.convolve(x, np.ones(w), 'valid') / w

data = np.array( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

print(moving_average(data,3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


In [24]:
def moving_average(x, w):
    return np.array([sum(x[i:i+3])/3 for i in range(len(x)) if len(x[i:i+3]) == 3])


data = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

print(moving_average(data,3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
